/* ApnaPan service worker — generated by _build/build.py.
   Caches the schemes shell, the six cards and the fonts, so a woman who has
   opened the app once can use it with no network: the quiz, the cards and the
   "request help" tap all keep working; requests queue and send later. */
const VERSION = "apnapan-2026-09-29";
const PRECACHE = [
  "",
  "schemes/",
  "schemes/mudra/",
  "schemes/stand-up-india/",
  "schemes/ayushman-bharat/",
  "schemes/nrlm-shg/",
  "schemes/pm-vishwakarma/",
  "schemes/odop/",
  "schemes/trainer-notes/",
  "assets/css/styles.css",
  "assets/css/fonts.css",
  "assets/js/schemes-data.js",
  "assets/js/schemes.js",
  "assets/js/data.js",
  "assets/js/i18n-data.js",
  "assets/js/i18n.js",
  "assets/js/app.js",
  "assets/favicon.svg",
  "assets/icons/icon-192.png",
  "assets/fonts/marcellus-latin.woff2",
  "assets/fonts/inter-latin.woff2",
  "assets/fonts/inter-latin-ext.woff2",
  "assets/fonts/noto-sans-kannada-kannada.woff2",
  "assets/fonts/noto-sans-kannada-latin.woff2",
  "assets/fonts/noto-sans-devanagari-devanagari.woff2",
  "assets/fonts/noto-sans-devanagari-latin.woff2"
];

self.addEventListener("install", (e) => {
  e.waitUntil((async () => {
    const c = await caches.open(VERSION);
    // one bad URL must not abort the whole install
    await Promise.all(PRECACHE.map((url) => c.add(new Request(url, {cache: "reload"})).catch(() => {})));
    self.skipWaiting();
  })());
});

self.addEventListener("activate", (e) => {
  e.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k !== VERSION).map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});

const isSchemes = (url) => new URL(url).pathname.includes("/schemes/");

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;                       // help requests go straight to the network
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;        // WhatsApp, phone links, fonts CDNs

  // pages: cached first (they are precached), then network, then the hub
  if (req.mode === "navigate") {
    event.respondWith((async () => {
      const cache = await caches.open(VERSION);
      const hit = await cache.match(req, {ignoreSearch: true});
      const net = fetch(req).then((res) => {
        if (res && res.ok) cache.put(req, res.clone());
        return res;
      }).catch(() => null);
      if (hit) { net; return hit; }
      const fresh = await net;
      if (fresh) return fresh;
      const hub = await cache.match("schemes/");
      if (isSchemes(req.url) && hub) return hub;
      return new Response(
        "<!doctype html><meta charset=utf-8><meta name=viewport content='width=device-width,initial-scale=1'>" +
        "<body style='font:16px system-ui;padding:2rem;background:#F7F3EC;color:#2E2013'>" +
        "<h1>You are offline</h1><p>Open the <a href='./schemes/'>Government Schemes</a> section — it works offline.</p>",
        {status: 200, headers: {"Content-Type": "text/html; charset=utf-8"}});
    })());
    return;
  }

  // static assets: serve from cache, refresh in the background
  event.respondWith((async () => {
    const cache = await caches.open(VERSION);
    const hit = await cache.match(req, {ignoreSearch: true});
    const net = fetch(req).then((res) => {
      if (res && res.ok) cache.put(req, res.clone());
      return res;
    }).catch(() => null);
    return hit || (await net) || Response.error();
  })());
});
