#!/usr/bin/env python3
"""Splice the dashboard's data block into dashboard/index.html.

The dashboard is a standalone page (no build step to run it), but its numbers
must be the same numbers the website is built from. Rather than keep two copies
in sync by hand, this script reads _build/content.py — the single source of
truth — and rewrites the marked block inside dashboard/index.html.

    python3 _build/app_data.py          # regenerate the block
    _build/test_app.py                  # asserts the two agree (fails the build if they drift)
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

import content as C  # noqa: E402

TARGET = os.path.join(ROOT, "dashboard", "index.html")
MARKER = "  /* __APNAPAN_DATA__ */"
GENERATED_NOTICE = ("  /* Data block — generated by _build/app_data.py from _build/content.py. "
                    "Do not hand-edit. */")


def build_data():
    makers, farmers = {}, {}
    for p in C.PRODUCTS:
        m = p["made_by"]
        makers.setdefault(m["name"], {"name": m["name"], "role": m["role"],
                                      "since": m.get("since", ""), "quote": m.get("quote", "")})
        f = p["sourced"]
        farmers.setdefault(f["farmer"], {"name": f["farmer"], "village": f["village"], "district": f["district"],
                                         "crop": f["crop"], "since": f.get("since", ""), "quote": f.get("quote", "")})
    return {
        "impact": {k: {kk: C.IMPACT[k][kk] for kk in ("value", "suffix", "label", "sub", "icon")}
                   for k in ("women", "farmers", "children", "mandi", "training", "shipped")},
        "allocation": [{"name": a["name"], "pct": a["pct"]} for a in C.ALLOCATION],
        "education": [{k: e[k] for k in ("value", "suffix", "label", "sub", "icon")} for e in C.EDUCATION["stats"]],
        "makers": list(makers.values()),
        "farmers": list(farmers.values()),
        "products": [
            {
                "slug": p["slug"], "name": p["name"], "category": p["category"], "type": p["type"],
                "price": p["price"], "mrp": p["mrp"], "unit": p["unit"], "rating": p["rating"],
                "reviews_count": p["reviews_count"], "spice_level": p.get("spice_level", ""),
                "badges": p["badges"][:3], "shelf_life": p.get("shelf_life", ""),
                "maker": p["made_by"]["name"], "maker_role": p["made_by"]["role"],
                "farmer": p["sourced"]["farmer"], "village": p["sourced"]["village"],
                "district": p["sourced"]["district"], "crop": p["sourced"]["crop"],
            }
            for p in C.PRODUCTS
        ],
    }


def main():
    html = open(TARGET, encoding="utf-8").read()
    body = json.dumps(build_data(), ensure_ascii=False, indent=2)
    body = "\n".join(("  " + ln) if ln.strip() else ln for ln in body.splitlines())
    block = (GENERATED_NOTICE + "\n"
             "  var DATA = " + body.strip() + ";")

    # Idempotent: replace the previously generated block if there is one, otherwise
    # splice into the marker that ships in the page.
    pattern = re.compile(re.escape(GENERATED_NOTICE) + r"\n  var DATA = .*?\n  \};", re.S)
    if MARKER in html:
        html = html.replace(MARKER, block, 1)
        how = "inserted at the marker"
    elif pattern.search(html):
        html = pattern.sub(lambda m: block, html, count=1)
        how = "regenerated in place"
    else:
        print("!! could not find the marker or a previous data block in dashboard/index.html")
        print("   expected one of:")
        print("    ", MARKER.strip())
        print("    ", GENERATED_NOTICE.strip())
        return 1

    open(TARGET, "w", encoding="utf-8").write(html)
    d = build_data()
    assert html.count("var DATA = ") == 1, "more than one data block in the page"
    print(f"dashboard data block {how}: {len(d['products'])} products, {len(d['farmers'])} farmers, "
          f"{len(d['makers'])} makers, {len(d['allocation'])} allocation rows, {len(d['education'])} fund stats")
    return 0


if __name__ == "__main__":
    sys.exit(main())
