# -*- coding: utf-8 -*-
"""
ApnaPan — static site build.

    cd apnapan && python3 _build/build.py

Reads content from _build/content.py + _build/i18n.py and writes the whole
site (HTML, sitemap, robots, JS data bundles) into the project root.
"""
import json
import os
import sys
import datetime

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

from content import BRAND, PRODUCTS, POSTS, IMPACT, FAQS_HOME           # noqa: E402
import render as R                                                      # noqa: E402
import pages as P                                                       # noqa: E402
from i18n import STR, LANGS, tree                                       # noqa: E402

TODAY = "2026-09-22"


def write(rel, text):
    path = os.path.join(ROOT, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"  {rel:52s} {len(text) / 1024:7.1f} KB")
    return path


def js_data():
    """Product + config bundle consumed by the cart, filters and checkout."""
    products = []
    for p in PRODUCTS:
        products.append({
            "slug": p["slug"], "name": p["name"], "name_kn": p["name_kn"], "name_hi": p["name_hi"],
            "category": p["category"], "type": p["type"], "unit": p["unit"],
            "price": p["price"], "mrp": p["mrp"], "sizes": p["sizes"], "img": p["img"],
            "rating": p["rating"], "reviews_count": p["reviews_count"], "tags": p["tags"],
            "short": p["short"],
            "made_by": p["made_by"]["name"], "farmer": p["sourced"]["farmer"],
        })
    cfg = {
        "brand": BRAND["name"], "wordmark": BRAND["wordmark"], "tagline": BRAND["tagline"],
        "freeShipOver": 599, "shipFee": 49, "codFee": 25, "schoolPct": 6,
        "razorpayKey": "",  # ← paste your Razorpay key id here (e.g. "rzp_test_XXXXXXXX") to enable live checkout
        "whatsapp": BRAND["whatsapp"], "phone": BRAND["phone"], "emails": BRAND["emails"],
        "products": products,
    }
    js = ("/* ApnaPan — generated by _build/build.py. Do not edit by hand. */\n"
          "window.APNAPAN = Object.assign(window.APNAPAN || {}, "
          + json.dumps(cfg, ensure_ascii=False, separators=(",", ":"))
          + ");\nwindow.APNAPAN.base = window.APNAPAN_BASE || '';\n")
    write("assets/js/data.js", js)

    i18n = ("/* ApnaPan — generated UI strings (en, kn, hi). */\n"
            "window.APNAPAN_LANGS = " + json.dumps(LANGS, ensure_ascii=False) + ";\n"
            "window.APNAPAN_I18N = " + json.dumps(tree(), ensure_ascii=False, separators=(",", ":")) + ";\n")
    write("assets/js/i18n-data.js", i18n)


def favicon():
    svg = '''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="64" height="64">
  <rect width="64" height="64" rx="14" fill="#1e4436"/>
  <g stroke="#e3a62b" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round" fill="none">
    <path d="M32 16c3.6 3.8 5.4 7.5 5.4 11.2S35.6 34.6 32 38c-3.6-3.4-5.4-7.2-5.4-10.9S28.4 19.8 32 16z"/>
    <path d="M32 38c-4.1-1.2-7.4-3.3-9.8-6.4-2.4-3.1-3.5-6.5-3.2-10.2 4 .5 7.4 2 10 4.6M32 38c4.1-1.2 7.4-3.3 9.8-6.4 2.4-3.1 3.5-6.5 3.2-10.2-4 .5-7.4 2-10 4.6"/>
    <path d="M15 41c4.6 3.6 10.2 5.4 17 5.4S44.4 44.6 49 41"/>
  </g>
</svg>'''
    write("assets/favicon.svg", svg)


def sitemap():
    urls = [("index.html", "1.0"), ("story.html", "0.9"), ("impact.html", "0.9"), ("shop.html", "1.0"),
            ("how-it-works.html", "0.8"), ("farmers.html", "0.8"), ("careers.html", "0.8"),
            ("blog.html", "0.7"), ("contact.html", "0.7"), ("checkout.html", "0.2")]
    for p in PRODUCTS:
        urls.append((f'products/{p["slug"]}.html', "0.9"))
    for p in POSTS:
        urls.append((f'blog/{p["slug"]}.html', "0.7"))
    items = "\n".join(
        f'  <url><loc>{BRAND["url"]}/{u}</loc><lastmod>{TODAY}</lastmod><changefreq>weekly</changefreq><priority>{pr}</priority></url>'
        for u, pr in urls)
    write("sitemap.xml", f'<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.w3.org/1999/xhtml/sitemap">\n'.replace(
        'http://www.w3.org/1999/xhtml/sitemap', 'http://www.sitemaps.org/schemas/sitemap/0.9') + items + "\n</urlset>\n")
    write("robots.txt", f"""# ApnaPan
User-agent: *
Allow: /
Disallow: /checkout.html
Sitemap: {BRAND['url']}/sitemap.xml
""")


def main():
    print("ApnaPan build")
    print("-" * 72)
    print("data bundles")
    js_data()
    print("assets")
    favicon()
    print("pages")
    write("index.html", P.home(R.Urls("")))
    write("story.html", P.story(R.Urls("")))
    write("impact.html", P.impact(R.Urls("")))
    write("shop.html", P.shop(R.Urls("")))
    write("how-it-works.html", P.how_it_works(R.Urls("")))
    write("careers.html", P.careers(R.Urls("")))
    write("farmers.html", P.farmers(R.Urls("")))
    write("blog.html", P.blog(R.Urls("")))
    write("contact.html", P.contact(R.Urls("")))
    write("checkout.html", P.checkout(R.Urls("")))
    write("404.html", P.not_found(R.Urls("")))
    for p in PRODUCTS:
        write(f'products/{p["slug"]}.html', P.product(R.Urls(".."), p))
    for p in POSTS:
        write(f'blog/{p["slug"]}.html', P.post_page(R.Urls(".."), p))
    sitemap()
    print("-" * 72)
    print(f"Built {11 + len(PRODUCTS) + len(POSTS)} pages · {len(PRODUCTS)} products · "
          f"{len(POSTS)} posts · {len(STR)} UI strings × {len(LANGS)} languages")


if __name__ == "__main__":
    main()
