# -*- coding: utf-8 -*-
"""
ApnaPan — static site build.

    cd apnapan && python3 _build/build.py

Reads content from _build/content.py + _build/i18n.py and writes the whole
site (HTML, sitemap, robots, JS data bundles) into the project root.
"""
import json
import os
import sys
import datetime

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

from content import BRAND, PRODUCTS, POSTS, IMPACT, FAQS_HOME           # noqa: E402
import render as R                                                      # noqa: E402
import pages as P                                                       # noqa: E402
from i18n import STR, LANGS, tree                                       # noqa: E402
from render import ROUTES, product_route, post_route, page_path, route   # noqa: E402

TODAY = "2026-09-22"


def write(rel, text):
    path = os.path.join(ROOT, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"  {rel:52s} {len(text) / 1024:7.1f} KB")
    return path


def js_data():
    """Product + config bundle consumed by the cart, filters and checkout."""
    products = []
    for p in PRODUCTS:
        products.append({
            "slug": p["slug"], "name": p["name"], "name_kn": p["name_kn"], "name_hi": p["name_hi"],
            "category": p["category"], "type": p["type"], "unit": p["unit"],
            "price": p["price"], "mrp": p["mrp"], "sizes": p["sizes"], "img": p["img"],
            "rating": p["rating"], "reviews_count": p["reviews_count"], "tags": p["tags"],
            "short": p["short"],
            "made_by": p["made_by"]["name"], "farmer": p["sourced"]["farmer"],
        })
    cfg = {
        "brand": BRAND["name"], "wordmark": BRAND["wordmark"], "tagline": BRAND["tagline"],
        "freeShipOver": 599, "shipFee": 49, "codFee": 25, "schoolPct": 6,
        "razorpayKey": "",  # ← paste your Razorpay key id here (e.g. "rzp_test_XXXXXXXX") to enable live checkout
        "whatsapp": BRAND["whatsapp"], "phone": BRAND["phone"], "emails": BRAND["emails"],
        "products": products,
    }
    js = ("/* ApnaPan — generated by _build/build.py. Do not edit by hand. */\n"
          "window.APNAPAN = Object.assign(window.APNAPAN || {}, "
          + json.dumps(cfg, ensure_ascii=False, separators=(",", ":"))
          + ");\nwindow.APNAPAN.base = window.APNAPAN_BASE || '';\n")
    write("assets/js/data.js", js)

    i18n = ("/* ApnaPan — generated UI strings (en, kn, hi). */\n"
            "window.APNAPAN_LANGS = " + json.dumps(LANGS, ensure_ascii=False) + ";\n"
            "window.APNAPAN_I18N = " + json.dumps(tree(), ensure_ascii=False, separators=(",", ":")) + ";\n")
    write("assets/js/i18n-data.js", i18n)


def favicon():
    svg = '''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="64" height="64">
  <rect width="64" height="64" rx="14" fill="#1e4436"/>
  <g stroke="#e3a62b" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round" fill="none">
    <path d="M32 16c3.6 3.8 5.4 7.5 5.4 11.2S35.6 34.6 32 38c-3.6-3.4-5.4-7.2-5.4-10.9S28.4 19.8 32 16z"/>
    <path d="M32 38c-4.1-1.2-7.4-3.3-9.8-6.4-2.4-3.1-3.5-6.5-3.2-10.2 4 .5 7.4 2 10 4.6M32 38c4.1-1.2 7.4-3.3 9.8-6.4 2.4-3.1 3.5-6.5 3.2-10.2-4 .5-7.4 2-10 4.6"/>
    <path d="M15 41c4.6 3.6 10.2 5.4 17 5.4S44.4 44.6 49 41"/>
  </g>
</svg>'''
    write("assets/favicon.svg", svg)


def sitemap():
    urls = [("", "1.0"), ("our-story/", "0.9"), ("our-impact/", "0.9"), ("shop/", "1.0"),
            ("how-it-works/", "0.8"), ("for-farmers/", "0.8"), ("careers/", "0.8"),
            ("blog/", "0.7"), ("contact/", "0.7")]
    for p in PRODUCTS:
        urls.append((product_route(p["slug"]), "0.9"))
    for p in POSTS:
        urls.append((post_route(p["slug"]), "0.7"))
    urls.append(("dashboard/", "0.5"))          # partner dashboard (hand-written page, see dashboard/index.html)
    items = "\n".join(
        f'  <url><loc>{BRAND["url"]}/{u}</loc><lastmod>{TODAY}</lastmod><changefreq>weekly</changefreq><priority>{pr}</priority></url>'
        for u, pr in urls)
    write("sitemap.xml", '<?xml version="1.0" encoding="UTF-8"?>\n'
          '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + items + "\n</urlset>\n")
    write("robots.txt", f"""# ApnaPan
User-agent: *
Allow: /
Disallow: /checkout/
Disallow: /dashboard/
Sitemap: {BRAND['url']}/sitemap.xml
""")


def legacy_redirects():
    """Old .html URLs keep working: every one 301s (via redirect stub) to its
    clean route, so no bookmark, share link or stale search result 404s.
    Delete this function and the stubs it writes if you never had live .html URLs."""
    # Only the paths that were genuinely live before the routes changed.
    pairs = [("index.html", route("home")), ("story.html", route("story")),
             ("impact.html", route("impact")), ("shop.html", route("shop")),
             ("how-it-works.html", route("how")), ("farmers.html", route("farmers")),
             ("careers.html", route("careers")), ("blog.html", route("blog")),
             ("contact.html", route("contact")), ("checkout.html", route("checkout"))]
    for p in PRODUCTS:
        pairs.append((f'products/{p["slug"]}.html', product_route(p["slug"])))
    for p in POSTS:
        pairs.append((f'blog/{p["slug"]}.html', post_route(p["slug"])))

    count = 0
    for old, new in pairs:
        if not new:
            continue
        depth = old.count("/")
        rel = ("../" * depth) + new            # relative hop from the old file
        full = f'{BRAND["url"]}/{new}'
        stub = f"""<!DOCTYPE html>
<html lang="en-IN">
<head>
<meta charset="utf-8">
<title>Moved — {BRAND["name"]}</title>
<link rel="canonical" href="{full}">
<meta name="robots" content="noindex, follow">
<meta http-equiv="refresh" content="0; url={rel}">
<script>location.replace("{rel}" + location.hash);</script>
</head>
<body>
<p>This page has moved to <a href="{rel}">{full}</a>.</p>
</body>
</html>
"""
        write(old, stub)
        count += 1
    print(f"  ({count} legacy .html paths redirect to clean routes)")


def main():
    print("ApnaPan build")
    print("-" * 72)
    print("data bundles")
    js_data()
    print("assets")
    favicon()
    write(".nojekyll", "")   # stop GitHub Pages from running Jekyll on the output
    print("pages")
    pages = [
        ("home",     P.home,     0), ("story",  P.story,  1), ("impact", P.impact, 1),
        ("shop",     P.shop,     1), ("how",    P.how_it_works, 1),
        ("farmers",  P.farmers,  1), ("careers", P.careers, 1),
        ("blog",     P.blog,     1), ("contact", P.contact, 1), ("checkout", P.checkout, 1),
    ]
    for name, fn, depth in pages:
        write(page_path(name), fn(R.Urls(depth)))
    write(page_path("notfound"), P.not_found(R.Urls(0)))
    for p in PRODUCTS:
        write(page_path("product", p["slug"]), P.product(R.Urls(2), p))
    for p in POSTS:
        write(page_path("post", p["slug"]), P.post_page(R.Urls(2), p))
    print("redirects")
    legacy_redirects()
    sitemap()
    print("-" * 72)
    print(f"Built {10 + len(PRODUCTS) + len(POSTS)} routed pages · {len(PRODUCTS)} products · "
          f"{len(POSTS)} posts · {len(STR)} UI strings × {len(LANGS)} languages")


if __name__ == "__main__":
    main()
