# -*- coding: utf-8 -*-
"""
ApnaPan — single source of truth for all site content.
Edit values here, then run:  python3 _build/build.py
Every number marked (SAMPLE) is illustrative — replace with your audited figures
before publishing. See README.md > "Replace before you go live".
"""

BRAND = {
    "name": "ApnaPan",
    "wordmark": "APNAPAN",
    "tagline": "Real Food • True Care • Live More",
    "legal": "ApnaPan Foods Pvt. Ltd.",
    "founded": 2019,
    "pitch": "Farm-direct spices, masalas and pickles — made by a women-run factory, and every jar funds a child's education.",
    "domain": "apnapan.in",
    "url": "https://www.apnapan.in",
    "phone_display": "+91 90000 00000",
    "phone": "+919000000000",
    "whatsapp": "919000000000",
    "emails": {
        "hello": "hello@apnapan.in",
        "farmers": "farmers@apnapan.in",
        "careers": "careers@apnapan.in",
        "csr": "csr@apnapan.in",
    },
    "addresses": [
        {"label": "Factory & Quality Lab", "lines": ["Plot 42, KIADB Industrial Area", "Doddaballapur, Bengaluru Rural", "Karnataka 561203"],
         "note": "Visits by appointment — Tue & Thu, 10am–4pm"},
        {"label": "Office & Experience Store", "lines": ["2nd Floor, Sri Vinayaka Complex", "Yelahanka New Town, Bengaluru", "Karnataka 560064"],
         "note": "Mon–Sat, 9:30am–6:30pm"},
    ],
    "hours": "Mon–Sat, 9:30am – 6:30pm IST",
    "social": [
        {"name": "Instagram", "url": "https://instagram.com/", "icon": "instagram"},
        {"name": "Facebook", "url": "https://facebook.com/", "icon": "facebook"},
        {"name": "YouTube", "url": "https://youtube.com/", "icon": "youtube"},
        {"name": "LinkedIn", "url": "https://linkedin.com/", "icon": "linkedin"},
    ],
    "reg": {
        "fssai": "FSSAI Lic. No. 11223344556677 (SAMPLE)",
        "gstin": "GSTIN 29ABCDE1234F1Z5 (SAMPLE)",
        "udyam": "Udyam Reg. UDYAM-KR-00-0000000 (SAMPLE)",
    },
}

NAV = [
    {"key": "nav.home", "href": "index.html"},
    {"key": "nav.story", "href": "story.html"},
    {"key": "nav.impact", "href": "impact.html"},
    {"key": "nav.shop", "href": "shop.html"},
    {"key": "nav.how", "href": "how-it-works.html"},
    {"key": "nav.farmers", "href": "farmers.html"},
    {"key": "nav.careers", "href": "careers.html"},
    {"key": "nav.blog", "href": "blog.html"},
    {"key": "nav.contact", "href": "contact.html"},
]

# ---------------------------------------------------------------- categories
CATEGORIES = [
    {"id": "masala", "label": "Spice Masalas", "blurb": "Slow-roasted, stone-ground blends for Karnataka's favourite dishes."},
    {"id": "mix", "label": "Ready Mixes", "blurb": "Breakfast and tiffin in fifteen minutes — no preservatives, no shortcuts."},
    {"id": "pickle", "label": "Pickles & Thokku", "blurb": "Sun-cured in small batches, exactly the way it is made at home."},
    {"id": "whole", "label": "Whole & Ground Spices", "blurb": "Single-origin spices, cleaned and ground at our own unit."},
]

TRUST_BADGES = [
    {"icon": "women", "title": "Women-led enterprise", "text": "9 of 10 team members are women, including every supervisor."},
    {"icon": "farm", "title": "Farm-direct sourcing", "text": "No middlemen. We buy at the farm gate and pay in 7 days."},
    {"icon": "shield", "title": "FSSAI licensed unit", "text": "Licensed kitchen, batch-tested in our own QC lab."},
    {"icon": "leaf", "title": "No preservatives", "text": "No artificial colours, no additives, no anti-caking agents."},
    {"icon": "school", "title": "Education funded", "text": "Every purchase pays into our employees' children's school fund."},
    {"icon": "pin", "title": "Made in Karnataka", "text": "Sourced, processed and packed within 200 km of Bengaluru."},
]

# ------------------------------------------------------------------ impact
IMPACT = {
    "farmers": {"value": 480, "suffix": "+", "label": "Farmer partners", "sub": "across 6 districts & 34 villages", "icon": "farm"},
    "women": {"value": 128, "suffix": "", "label": "Women employed", "sub": "processing, QC, packaging, field & office", "icon": "women"},
    "children": {"value": 216, "suffix": "", "label": "Children supported", "sub": "school fees, books and Class 10 coaching", "icon": "school"},
    "mandi": {"value": 22, "suffix": "%", "label": "Above mandi price", "sub": "average premium paid to farmers in 2025", "icon": "rupee"},
    "training": {"value": 4800, "suffix": "+ hrs", "label": "Skill training", "sub": "food safety, machine handling, quality, accounts", "icon": "spark"},
    "shipped": {"value": 96000, "suffix": "+", "label": "Packs shipped in 2025", "sub": "to homes, stores and gifting partners", "icon": "box"},
}

ALLOCATION = [
    {"name": "Paid to farmers", "pct": 52, "color": "#1e4436"},
    {"name": "Wages for our women's team", "pct": 21, "color": "#b4552d"},
    {"name": "Education fund for employees' children", "pct": 6, "color": "#e3a62b"},
    {"name": "Ingredients, glass & packaging", "pct": 12, "color": "#7a6a5a"},
    {"name": "Logistics & delivery", "pct": 5, "color": "#c79a3b"},
    {"name": "Operations & platform", "pct": 4, "color": "#a99b8c"},
]

EDUCATION = {
    "headline": "The Class 10 Fund",
    "intro": ("Every child of an ApnaPan employee is enrolled the month their parent joins. From Class 1 to Class 9 we cover "
              "books, uniforms and a school bag. In Class 10 — the year that decides a child's next ten years — the fund "
              "covers the whole year."),
    "what_it_covers": [
        "Full school and exam fees for the Class 10 year",
        "Textbooks, notebooks, uniforms and a school bag",
        "Evening coaching in maths and science, at our unit or online",
        "A study tablet for children who score above 75% in the Class 9 exam",
        "Bus or cycle pass so no child drops out over travel",
        "₹5,000 merit grant on passing Class 10 with distinction",
        "Fees for Class 11 & 12 continue for children who stay in school",
    ],
    "stats": [
        {"value": 216, "suffix": "", "label": "Children in the fund", "sub": "since the fund began in 2022", "icon": "school"},
        {"value": 96, "suffix": "%", "label": "Class 10 pass rate", "sub": "2025 cohort, against 78% district average*", "icon": "award"},
        {"value": 41, "suffix": "", "label": "Girls in Class 11 & 12", "sub": "first generation in their families", "icon": "book"},
        {"value": 38, "suffix": "", "label": "Children who joined in 2022", "sub": "the founding cohort, now in Class 12", "icon": "users"},
    ],
    "footnote": "*Illustrative figure — replace with your own audited programme data before publishing.",
}

# ----------------------------------------------------------------- products
PY = "₹"   # rupee sign

PRODUCTS = [
    {
        "slug": "bisibelebath-masala",
        "name": "Bisibelebath Masala",
        "name_kn": "ಬಿಸಿಬೇಳೆಬಾತ್ ಮಸಾಲೆ",
        "name_hi": "बिसिबेले बाथ मसाला",
        "category": "masala",
        "type": "Ground masala",
        "price": 185, "mrp": 215, "unit": "200 g",
        "sizes": [{"label": "200 g", "price": 185}, {"label": "500 g", "price": 415}],
        "img": "assets/images/products/bisibelebath-masala.jpg",
        "rating": 4.8, "reviews_count": 164,
        "tags": ["bestseller"],
        "badges": ["No preservatives", "Stone-ground", "Small batch"],
        "diet": ["Vegetarian", "No onion-garlic"],
        "short": "The Bengaluru classic — rice, dal and vegetable kootu in one pot. Deep, warm and properly spiced.",
        "short_kn": "ಬೆಂಗಳೂರಿನ ಮನೆಮಗಳು — ಒಂದೇ ಪಾತ್ರೆಯಲ್ಲಿ ಬಿಸಿಬೇಳೆಬಾತ್. ಆಳವಾದ ಸುವಾಸನೆ, ಸರಿಯಾದ ಖಾರ.",
        "short_hi": "बेंगलुरु का क्लासिक — एक ही बर्तन में बिसिबेले बाथ। गहरा स्वाद, सही मसाला।",
        "story": ("Our most-loved blend, and the one we make most carefully. Byadagi chilli gives the colour, roasted chana dal and "
                  "urad dal give the body, and a little marathi moggu and stone flower give that aroma you cannot get from a "
                  "factory blend. Roasted in small batches every Tuesday and Friday, ground on a slow stone mill so the oils "
                  "stay in the powder instead of burning off."),
        "ingredients": [
            {"name": "Byadagi chilli", "note": "Rudrappa H., Byadagi taluk, Haveri — since 2022"},
            {"name": "Coriander seed", "note": "Savitramma P., Ron taluk, Gadag — since 2021"},
            {"name": "Roasted chana dal & urad dal", "note": "Kalaburagi farmer collective, 60 members"},
            {"name": "Dry coconut (copra)", "note": "Tiptur, Tumakuru district"},
            {"name": "Cinnamon, clove, marathi moggu, stone flower", "note": "Western Ghats, small lots"},
            {"name": "Turmeric", "note": "Zinc-rich Mysuru turmeric, ground at our unit"},
        ],
        "nutrition": [("Energy", "402 kcal"), ("Protein", "12.6 g"), ("Carbohydrates", "54.2 g"), ("— of which sugars", "2.1 g"),
                      ("Fat", "13.4 g"), ("— of which saturated", "5.8 g"), ("Dietary fibre", "17.9 g"), ("Sodium", "1.9 g")],
        "shelf_life": "9 months from the date of packing",
        "storage": "Store in an airtight jar, away from sunlight. Use a dry spoon only.",
        "how_to_use": ("For 4 people: 1½ cups rice, ¾ cup toor dal, 2 cups mixed vegetables, 3 heaped tsp of this masala, "
                       "small lemon-sized tamarind, 2 tbsp ghee. Pressure-cook rice and dal, cook vegetables with tamarind and "
                       "masala, then fold everything together and finish with ghee and fried cashews."),
        "spice_level": "Medium",
        "made_by": {"name": "Shivamma B.", "role": "Masala unit lead", "since": "2021",
                    "quote": "I check every roast by smell. If the chana dal smells bitter, the whole batch goes back."},
        "sourced": {"farmer": "Rudrappa H.", "village": "Byadagi", "district": "Haveri", "crop": "Byadagi chilli", "since": "2022",
                    "quote": "Before, I sold to whoever came to the gate. Now I know the price before I harvest, and the money comes in a week."},
        "reviews": [
            {"name": "Ananya R.", "city": "Bengaluru", "rating": 5, "date": "Aug 2026",
             "text": "Tastes exactly like my grandmother's. The aroma when you open the jar is the giveaway — it is fresh, not dusty."},
            {"name": "Manoj S.", "city": "Mysuru", "rating": 5, "date": "Jul 2026",
             "text": "I use three teaspoons for four people and it is spot on. No need to add anything else except tamarind and ghee."},
            {"name": "Farida K.", "city": "Hyderabad", "rating": 4, "date": "Jun 2026",
             "text": "Lovely depth. Slightly less spicy than what I make at home, so I add one extra chilli — but the flavour is beautiful."},
        ],
    },
    {
        "slug": "vangi-bath-masala",
        "name": "Vangi Bath Masala",
        "name_kn": "ವಾಂಗಿಬಾತ್ ಮಸಾಲೆ",
        "name_hi": "वांगी बाथ मसाला",
        "category": "masala",
        "type": "Ground masala",
        "price": 175, "mrp": 199, "unit": "200 g",
        "sizes": [{"label": "200 g", "price": 175}, {"label": "500 g", "price": 395}],
        "img": "assets/images/products/vangi-bath-masala.jpg",
        "rating": 4.7, "reviews_count": 118,
        "tags": [],
        "badges": ["No preservatives", "Stone-ground", "Small batch"],
        "diet": ["Vegetarian", "Vegan"],
        "short": "Brinjal rice with the sweet-sour balance Karnataka gets right. Also excellent with potatoes or capsicum.",
        "short_kn": "ಬದನೆಕಾಯಿ ಪಲ್ಯಕ್ಕೆ ಸರಿಯಾದ ಸಿಹಿ-ಹುಳಿ ಸಮತೋಲನ. ಆಲೂಗಡ್ಡೆ ಅಥವಾ ದೊಣ್ಣೆಮೆಣಸಿನಕಾಯಿಗೂ ಚೆನ್ನಾಗಿದೆ.",
        "short_hi": "बैंगन चावल का सही खट्टा-मीठा संतुलन। आलू या शिमला मिर्च के साथ भी बढ़िया।",
        "story": ("Vangi bath lives or dies on its masala: too much chilli and the brinjal disappears, too little and it tastes like "
                  "plain rice. We roast the spices separately — coriander and cumin first, then the dals, then the Byadagi chilli — "
                  "so each one reaches its own point before we grind them together with dry coconut and a touch of jaggery."),
        "ingredients": [
            {"name": "Byadagi chilli", "note": "Rudrappa H., Byadagi taluk, Haveri"},
            {"name": "Coriander seed", "note": "Savitramma P., Ron taluk, Gadag"},
            {"name": "Roasted chana dal & urad dal", "note": "Kalaburagi farmer collective"},
            {"name": "Dry coconut (copra)", "note": "Tiptur, Tumakuru district"},
            {"name": "Tamarind powder", "note": "Sun-dried, ground at our unit"},
            {"name": "Jaggery, curry leaf, asafoetida", "note": "Mandya jaggery, Hassan curry leaf"},
        ],
        "nutrition": [("Energy", "396 kcal"), ("Protein", "11.8 g"), ("Carbohydrates", "56.4 g"), ("— of which sugars", "4.6 g"),
                      ("Fat", "12.9 g"), ("— of which saturated", "5.2 g"), ("Dietary fibre", "16.2 g"), ("Sodium", "2.1 g")],
        "shelf_life": "9 months from the date of packing",
        "storage": "Store in an airtight jar, away from sunlight. Use a dry spoon only.",
        "how_to_use": ("For 4 people: 2 cups cooked rice, 6 small brinjals, 3 tsp masala, 1 tbsp tamarind paste, 1 tsp jaggery. "
                       "Fry sliced brinjals in oil, add masala with a splash of water, cook till the oil separates, then fold into warm rice."),
        "spice_level": "Medium",
        "made_by": {"name": "Lakshmidevi N.", "role": "Roasting & grinding operator", "since": "2022",
                    "quote": "The smell tells you when the coriander is ready. Two seconds later and the batch is bitter."},
        "sourced": {"farmer": "Savitramma P.", "village": "Ron taluk", "district": "Gadag", "crop": "Coriander seed", "since": "2021",
                    "quote": "They weigh in front of me and the rate is written on the slip. I have never had to ask twice for money."},
        "reviews": [
            {"name": "Sneha M.", "city": "Bengaluru", "rating": 5, "date": "Sep 2026",
             "text": "I use it for vangi bath and for potato palya. Both taste like a wedding plate — which is the highest compliment I know."},
            {"name": "Prakash V.", "city": "Davangere", "rating": 4, "date": "May 2026",
             "text": "Very good balance of sweet and sour. I would like a little more chilli, but my wife thinks it is perfect."},
        ],
    },
    {
        "slug": "ghee-roast-masala",
        "name": "Ghee Roast Masala",
        "name_kn": "ತುಪ್ಪ ರೋಸ್ಟ್ ಮಸಾಲೆ",
        "name_hi": "घी रोस्ट मसाला",
        "category": "masala",
        "type": "Ground masala",
        "price": 195, "mrp": 219, "unit": "150 g",
        "sizes": [{"label": "150 g", "price": 195}, {"label": "400 g", "price": 455}],
        "img": "assets/images/products/ghee-roast-masala.jpg",
        "rating": 4.9, "reviews_count": 142,
        "tags": ["bestseller"],
        "badges": ["No preservatives", "Stone-ground", "High chilli"],
        "diet": ["Vegetarian", "Gluten-free"],
        "short": "The Mangalorean ghee roast, in a jar. Use it for chicken, prawns, mushrooms or paneer.",
        "short_kn": "ಮಂಗಳೂರಿನ ತುಪ್ಪ ರೋಸ್ಟ್, ಜಾರ್‌ನಲ್ಲಿ. ಚಿಕನ್, ಸೀಗಡಿ, ಅಣಬೆ ಅಥವಾ ಪನೀರ್‌ಗೆ.",
        "short_hi": "मंगलोर का घी रोस्ट, जार में। चिकन, झींगा, मशरूम या पनीर के लिए।",
        "story": ("A coastal Karnataka recipe from our Udipi-born supervisor, Sunita, who insists on three things: Byadagi chilli for "
                  "colour, kashmiri chilli for a clean heat, and enough fenugreek to make the whole masala smell like a "
                  "kitchen at 6am. It is sharp, tangy and unapologetic — start with one spoon and work your way up."),
        "ingredients": [
            {"name": "Byadagi chilli & Kashmiri chilli", "note": "Haveri, blended at our unit"},
            {"name": "Coriander seed", "note": "Savitramma P., Ron taluk, Gadag"},
            {"name": "Cumin & fenugreek", "note": "Koppal district"},
            {"name": "Curry leaf", "note": "Buyers' own farms, Hassan"},
            {"name": "Tamarind & jaggery", "note": "Mandya jaggery, sun-dried tamarind"},
            {"name": "Black pepper", "note": "Kodagu, smallholder lots"},
        ],
        "nutrition": [("Energy", "388 kcal"), ("Protein", "13.5 g"), ("Carbohydrates", "49.8 g"), ("— of which sugars", "3.4 g"),
                      ("Fat", "15.2 g"), ("— of which saturated", "6.1 g"), ("Dietary fibre", "19.4 g"), ("Sodium", "1.6 g")],
        "shelf_life": "9 months from the date of packing",
        "storage": "Store in an airtight jar, away from sunlight. Keeps best in the fridge after opening.",
        "how_to_use": ("500 g of chicken or mushrooms, 3 heaped tsp masala, 3 tbsp ghee, 1 tbsp curd, tamarind to taste. "
                       "Marinate for 30 minutes, roast on a heavy pan on medium heat until the ghee separates and coats the pieces."),
        "spice_level": "Hot",
        "made_by": {"name": "Sunita K.", "role": "Production supervisor", "since": "2020",
                    "quote": "I grew up watching my mother make this for the church feast. The measurement is not a recipe — it is a memory."},
        "sourced": {"farmer": "Ibrahim S.", "village": "Shiggaon", "district": "Haveri", "crop": "Byadagi chilli & maize", "since": "2023",
                    "quote": "They asked for chilli with low moisture and paid a better rate for it. So now I dry it properly instead of selling it damp."},
        "reviews": [
            {"name": "Rohan D.", "city": "Mangaluru", "rating": 5, "date": "Sep 2026",
             "text": "I am from Mangaluru and I am fussy. This is the real thing — sharp, tangy, and it makes your kitchen smell incredible."},
            {"name": "Aarti G.", "city": "Pune", "rating": 5, "date": "Aug 2026",
             "text": "Used it on paneer and then on mushrooms the same week. Both were restaurant-level."},
            {"name": "Kiran B.", "city": "Bengaluru", "rating": 4, "date": "Jul 2026",
             "text": "Punchy. Followed the jar instructions exactly and the masala clung to the chicken beautifully."},
        ],
    },
    {
        "slug": "maddur-vada-mix",
        "name": "Maddur Vada Mix",
        "name_kn": "ಮದ್ದೂರು ವಡೆ ಮಿಕ್ಸ್",
        "name_hi": "मद्दूर वड़ा मिक्स",
        "category": "mix",
        "type": "Ready mix",
        "price": 145, "mrp": 165, "unit": "250 g",
        "sizes": [{"label": "250 g", "price": 145}, {"label": "500 g", "price": 270}],
        "img": "assets/images/products/maddur-vada-mix.jpg",
        "rating": 4.7, "reviews_count": 96,
        "tags": ["new"],
        "badges": ["No preservatives", "Just add water", "Makes 22–25 vadas"],
        "diet": ["Vegetarian", "No onion-garlic"],
        "short": "Crisp outside, soft inside, and it still tastes like the ones on the highway. Add water, rest, fry.",
        "short_kn": "ಹೊರಗೆ ಗರಿಗರಿ, ಒಳಗೆ ಮೆದು — ಹೆದ್ದಾರಿ ಮದ್ದೂರು ವಡೆಯ ರುಚಿಯೇ. ನೀರು ಸೇರಿಸಿ, ವಿಶ್ರಾಂತಿ ಕೊಟ್ಟು ಕರಿಯಿರಿ.",
        "short_hi": "बाहर से कुरकुरा, अंदर से मुलायम — हाईवे जैसा स्वाद। पानी मिलाइए, रखिए, तलिए।",
        "story": ("Maddur vada is a Karnataka institution: the tea-stop snack between Bengaluru and Mysuru, eaten hot with coconut "
                  "chutney and an argument about whose grandmother made it better. Our mix is roasted semolina, rice flour, "
                  "onion-free spice paste and a generous amount of curry leaf and fried gram — the exact thing that makes a "
                  "vada crunch. No raising agents, no preservatives."),
        "ingredients": [
            {"name": "Roasted semolina (rava)", "note": "Milled in Tumakuru, roasted at our unit"},
            {"name": "Rice flour", "note": "Mandya paddy, milled locally"},
            {"name": "Fried gram & curry leaf", "note": "Hassan district"},
            {"name": "Coriander seed, cumin, green chilli", "note": "Gadag & Kolar"},
            {"name": "Byadagi chilli", "note": "Haveri"},
            {"name": "Salt, asafoetida", "note": "No artificial colour, no raising agent"},
        ],
        "nutrition": [("Energy", "361 kcal"), ("Protein", "8.4 g"), ("Carbohydrates", "68.2 g"), ("— of which sugars", "1.8 g"),
                      ("Fat", "5.6 g"), ("— of which saturated", "1.2 g"), ("Dietary fibre", "6.9 g"), ("Sodium", "2.4 g")],
        "shelf_life": "6 months from the date of packing",
        "storage": "Keep the pouch sealed and dry. Transfer to an airtight box after opening.",
        "how_to_use": ("Mix 250 g of mix with 1½ cups of water and 2 tbsp hot oil. Rest for 15 minutes. Shape into thin patties on a "
                       "greased plate and fry on medium heat until golden. Serve hot with coconut chutney."),
        "spice_level": "Mild",
        "made_by": {"name": "Renuka T.", "role": "Ready-mix line operator", "since": "2023",
                    "quote": "We test every batch by frying it. If the vada drinks oil, the roast is wrong and we redo it."},
        "sourced": {"farmer": "Chandregowda M.", "village": "Bellur", "district": "Mandya", "crop": "Paddy & sugarcane", "since": "2023",
                    "quote": "I sell my paddy for their rice flour. It is a small order for them but it pays my daughter's hostel fees."},
        "reviews": [
            {"name": "Divya S.", "city": "Bengaluru", "rating": 5, "date": "Aug 2026",
             "text": "I have made Maddur vada from scratch twice and both times ended up with hockey pucks. This mix worked the first time."},
            {"name": "Suresh N.", "city": "Mysuru", "rating": 4, "date": "Jun 2026",
             "text": "Very close to the highway taste. Next time I will add fresh onions and green chilli to my side of the dough."},
        ],
    },
    {
        "slug": "akki-rotti-mix",
        "name": "Akki Rotti Mix",
        "name_kn": "ಅಕ್ಕಿ ರೊಟ್ಟಿ ಮಿಕ್ಸ್",
        "name_hi": "अक्की रोट्टी मिक्स",
        "category": "mix",
        "type": "Ready mix",
        "price": 135, "mrp": 155, "unit": "250 g",
        "sizes": [{"label": "250 g", "price": 135}, {"label": "500 g", "price": 255}],
        "img": "assets/images/products/akki-rotti-mix.jpg",
        "rating": 4.6, "reviews_count": 78,
        "tags": [],
        "badges": ["No preservatives", "Just add hot water", "Makes 8–10 rottis"],
        "diet": ["Vegetarian", "Gluten-free"],
        "short": "Rural Karnataka's breakfast of choice — soft rice rotis on a hot griddle in minutes.",
        "short_kn": "ಕರ್ನಾಟಕದ ಹಳ್ಳಿಗಳ ಬೆಳಗಿನ ಊಟ — ಬಿಸಿ ಕಾವಲಿಯ ಮೇಲೆ ಮೆದುವಾದ ಅಕ್ಕಿ ರೊಟ್ಟಿ.",
        "short_hi": "गाँवों का नाश्ता — गरम तवे पर मुलायम चावल की रोटी, कुछ ही मिनटों में।",
        "story": ("Akki rotti is the recipe that every family in old Mysuru makes differently and defends fiercely. Ours uses Mandya "
                  "rice flour, a little maida-free binding of fried gram, plenty of curry leaf, coriander, cumin and coconut. "
                  "Adding hot water is the trick — it cooks the flour slightly so the dough spreads without tearing."),
        "ingredients": [
            {"name": "Rice flour", "note": "Mandya paddy, stone-milled"},
            {"name": "Fried gram", "note": "Hassan district"},
            {"name": "Dry coconut", "note": "Tiptur, Tumakuru"},
            {"name": "Curry leaf, coriander, cumin", "note": "Hassan & Gadag"},
            {"name": "Green chilli & Byadagi chilli", "note": "Kolar & Haveri"},
            {"name": "Salt, sesame seed", "note": "No preservatives, no gluten"},
        ],
        "nutrition": [("Energy", "352 kcal"), ("Protein", "7.1 g"), ("Carbohydrates", "71.4 g"), ("— of which sugars", "1.2 g"),
                      ("Fat", "4.8 g"), ("— of which saturated", "1.6 g"), ("Dietary fibre", "5.4 g"), ("Sodium", "2.2 g")],
        "shelf_life": "6 months from the date of packing",
        "storage": "Keep the pouch sealed and dry. Use within 8 weeks of opening.",
        "how_to_use": ("Add 1 cup of hot water to 250 g of mix and knead into a soft dough. Rest 10 minutes. Spread by hand on a "
                       "hot tawa or banana leaf, drizzle oil, and cook both sides until brown patches appear."),
        "spice_level": "Mild",
        "made_by": {"name": "Bhavya R.", "role": "Packing team", "since": "2024",
                    "quote": "Before this job I did tailoring at home. Now I run the sealing machine and I am learning the mixer next month."},
        "sourced": {"farmer": "Nagaraju K.", "village": "Srirangapatna", "district": "Mandya", "crop": "Paddy", "since": "2024",
                    "quote": "They take a smaller quantity than the mill, but they pay on time and they do not reject the crop after loading."},
        "reviews": [
            {"name": "Vidya P.", "city": "Bengaluru", "rating": 5, "date": "Jul 2026",
             "text": "My mother used to make this every Sunday. Now my son asks for akki rotti before cricket practice."},
            {"name": "Harish G.", "city": "Tumakuru", "rating": 4, "date": "May 2026",
             "text": "Soft and easy to spread. I add grated carrot to mine — works well."},
        ],
    },
    {
        "slug": "lemon-rice-mix",
        "name": "Lemon Rice Mix",
        "name_kn": "ಚಿತ್ರಾನ್ನ ಮಿಕ್ಸ್",
        "name_hi": "लेमन राइस मिक्स",
        "category": "mix",
        "type": "Ready mix",
        "price": 120, "mrp": 140, "unit": "200 g",
        "sizes": [{"label": "200 g", "price": 120}, {"label": "400 g", "price": 230}],
        "img": "assets/images/products/lemon-rice-mix.jpg",
        "rating": 4.6, "reviews_count": 89,
        "tags": [],
        "badges": ["No preservatives", "Travel friendly", "No cooking of masala"],
        "diet": ["Vegetarian", "Vegan option"],
        "short": "Chitranna for lunch boxes, train journeys and days when nobody wants to cook. Fifteen minutes, one pan.",
        "short_kn": "ಲಂಚ್ ಬಾಕ್ಸ್, ರೈಲು ಪ್ರಯಾಣ ಅಥವಾ ಅಡುಗೆ ಮಾಡಲು ಮನಸ್ಸಿಲ್ಲದ ದಿನಗಳಿಗೆ ಚಿತ್ರಾನ್ನ. ಹದಿನೈದು ನಿಮಿಷ, ಒಂದೇ ಪಾತ್ರೆ.",
        "short_hi": "टिफ़िन, ट्रेन और जब खाना बनाने का मन न हो — चित्रान्न। पंद्रह मिनट, एक बर्तन।",
        "story": ("Chitranna is comfort food with a tang. Ours carries the roasted peanuts, fried gram, curry leaf and Byadagi chilli "
                  "separately from the turmeric-lemon base, so nothing turns soft in the pack. The result is a mix that still "
                  "crunches when you fold it into hot rice at the end."),
        "ingredients": [
            {"name": "Roasted peanut & fried gram", "note": "Koppal & Hassan, roasted at our unit"},
            {"name": "Byadagi chilli & turmeric", "note": "Haveri chilli, Mysuru turmeric"},
            {"name": "Curry leaf & mustard", "note": "Hassan district"},
            {"name": "Lemon powder", "note": "Freeze-dried, no synthetic citric acid"},
            {"name": "Asafoetida, salt", "note": "No preservatives, no colour"},
        ],
        "nutrition": [("Energy", "374 kcal"), ("Protein", "9.8 g"), ("Carbohydrates", "63.7 g"), ("— of which sugars", "3.6 g"),
                      ("Fat", "8.9 g"), ("— of which saturated", "1.7 g"), ("Dietary fibre", "7.2 g"), ("Sodium", "2.6 g")],
        "shelf_life": "6 months from the date of packing",
        "storage": "Keep the pouch sealed. Airtight box after opening so the peanuts stay crunchy.",
        "how_to_use": ("For 3 cups of cooked rice, heat 2 tbsp oil, add 3 tsp of the mix and a pinch of salt, then fold in the rice "
                       "off the heat. Squeeze in fresh lemon if you have it — half a lemon takes it from good to perfect."),
        "spice_level": "Mild",
        "made_by": {"name": "Shobha M.", "role": "Ready-mix line operator", "since": "2021",
                    "quote": "I pack the peanuts last so they are on top when you open it. Small thing, but people notice."},
        "sourced": {"farmer": "Basavaraj S.", "village": "Kukkanur", "district": "Koppal", "crop": "Groundnut", "since": "2022",
                    "quote": "Groundnut prices fall in a good year, which is the opposite of fair. A buying commitment in April gives me the courage to plant."},
        "reviews": [
            {"name": "Meera J.", "city": "Bengaluru", "rating": 5, "date": "Sep 2026",
             "text": "Sent this with my son on his school trip. He said it was the best thing in his tiffin box all week."},
            {"name": "Ashwin R.", "city": "Chennai", "rating": 4, "date": "Jun 2026",
             "text": "Great for quick dinners. I add fresh curry leaves and a squeeze of lemon to make it sing."},
        ],
    },
    {
        "slug": "mavina-midi-pickle",
        "name": "Mavina Midi Pickle",
        "name_kn": "ಮಾವಿನ ಮಿಡಿ ಉಪ್ಪಿನಕಾಯಿ",
        "name_hi": "कच्चे आम का अचार",
        "category": "pickle",
        "type": "Pickle",
        "price": 215, "mrp": 245, "unit": "250 g",
        "sizes": [{"label": "250 g", "price": 215}, {"label": "600 g", "price": 449}],
        "img": "assets/images/products/mavina-midi-pickle.jpg",
        "rating": 4.9, "reviews_count": 187,
        "tags": ["bestseller"],
        "badges": ["Sun-cured", "No preservatives", "Mustard oil"],
        "diet": ["Vegetarian", "Vegan", "Gluten-free"],
        "short": "Tiny whole baby mangoes cured in mustard and chilli. Sharp, chewy, and dangerously habit-forming.",
        "short_kn": "ಸಣ್ಣ ಮಾವಿನ ಮಿಡಿಗಳನ್ನು ಸಾಸಿವೆ ಮತ್ತು ಮೆಣಸಿನಲ್ಲಿ ಊರಿಟ್ಟ ಉಪ್ಪಿನಕಾಯಿ. ಖಾರ, ಕಡಿದು, ಮತ್ತೆ ಮತ್ತೆ ಬೇಕು.",
        "short_hi": "छोटे कच्चे आम, सरसों और मिर्च में — तीखा, चटपटा और लत लगाने वाला।",
        "short_usage": "Best with curd rice, dal rice, rotis or just a spoon on the side of anything.",
        "story": ("Baby mango pickle is a June project. The mangoes are picked while the stone is still soft — usually the last week of "
                  "May to mid-June — and must go into salt within a day of plucking. We split each midi at the tip, pack it with "
                  "hand-pounded mustard, Byadagi chilli, fenugreek and rock salt in mustard oil, and then it is simply sun and "
                  "time: fourteen days on our terrace, stirred every morning, no acetic acid and no preservatives."),
        "ingredients": [
            {"name": "Baby mango (midi)", "note": "Kolar & Ramanagara, picked late May–June"},
            {"name": "Cold-pressed mustard oil", "note": "Rajasthan mustard, pressed in Bengaluru"},
            {"name": "Byadagi chilli powder", "note": "Rudrappa H., Haveri"},
            {"name": "Hand-pounded mustard & fenugreek", "note": "Koppal"},
            {"name": "Rock salt", "note": "No refined salt, no acetic acid"},
            {"name": "Turmeric, asafoetida", "note": "Mysuru & Hassan"},
        ],
        "nutrition": [("Energy", "168 kcal"), ("Protein", "3.2 g"), ("Carbohydrates", "14.6 g"), ("— of which sugars", "5.1 g"),
                      ("Fat", "10.4 g"), ("— of which saturated", "1.3 g"), ("Dietary fibre", "4.8 g"), ("Sodium", "3.1 g")],
        "shelf_life": "18 months; improves for the first 6",
        "storage": "Always use a dry spoon. Keep the mangoes under the oil layer. Do not refrigerate before opening.",
        "how_to_use": "Serve 2–3 midis with curd rice, dal rice or chapati. The oil at the top is part of the pickle — spoon it over, do not drain it.",
        "spice_level": "Medium-hot",
        "made_by": {"name": "Gowramma D.", "role": "Pickle kitchen lead", "since": "2019",
                    "quote": "I have made this every June for thirty years at home. Now I make it for four thousand people. Same twelve kilos of mustard."},
        "sourced": {"farmer": "Shivakumar N.", "village": "Chikkaballapur", "district": "Chikkaballapur", "crop": "Mango (midi)", "since": "2021",
                    "quote": "The midi used to be the crop nobody wanted — too small for the market. Now it is the first harvest we look forward to."},
        "reviews": [
            {"name": "Sridevi K.", "city": "Bengaluru", "rating": 5, "date": "Aug 2026",
             "text": "This is exactly my mother's pickle. I bought one jar to try, and then three more the following week for my sisters."},
            {"name": "Naveen A.", "city": "Bengaluru", "rating": 5, "date": "Jul 2026",
             "text": "The salt is right, the mangoes are crunchy, and the oil is real mustard oil. Almost impossible to find these days."},
            {"name": "Latha M.", "city": "Hosur", "rating": 4, "date": "Jun 2026",
             "text": "Beautifully sharp. I would like a slightly larger jar size for a family of six."},
        ],
    },
    {
        "slug": "nellikai-pickle",
        "name": "Nellikai Pickle",
        "name_kn": "ನೆಲ್ಲಿಕಾಯಿ ಉಪ್ಪಿನಕಾಯಿ",
        "name_hi": "आँवला का अचार",
        "category": "pickle",
        "type": "Pickle",
        "price": 235, "mrp": 265, "unit": "400 g",
        "sizes": [{"label": "400 g", "price": 235}, {"label": "800 g", "price": 435}],
        "img": "assets/images/products/nellikai-pickle.jpg",
        "rating": 4.8, "reviews_count": 112,
        "tags": [],
        "badges": ["Sun-cured", "No preservatives", "Oil-free option"],
        "diet": ["Vegetarian", "Vegan", "Gluten-free"],
        "short": "Soft amla pieces in a thick, sour, chilli-tamarind masala. Two pieces after a heavy meal is the whole point.",
        "short_kn": "ದಪ್ಪ, ಹುಳಿ ಮಸಾಲೆಯಲ್ಲಿ ಮೆದುವಾದ ನೆಲ್ಲಿಕಾಯಿ ತುಣುಕುಗಳು. ಊಟದ ನಂತರ ಎರಡು ತುಣುಕು ಸಾಕು.",
        "short_hi": "मुलायम आँवला, गाढ़े खट्टे-तीखे मसाले में। भोजन के बाद दो टुकड़े — बस इतना ही।",
        "story": ("Nellikai — Indian gooseberry — is the most forgiving fruit in a pickle kitchen and the least forgiving in a good one. "
                  "If the fruit is not packed the day it is bought, it goes soft in the jar. We steam the amla lightly, dry it in "
                  "the shade and then layer it with tamarind, jaggery, Byadagi chilli and hand-pounded mustard. Made in "
                  "100-jar batches from December to February, when the amla is at its best."),
        "ingredients": [
            {"name": "Amla (nellikai)", "note": "Chitradurga & Tumakuru, Dec–Feb harvest"},
            {"name": "Tamarind & jaggery", "note": "Mandya jaggery, sun-dried tamarind"},
            {"name": "Byadagi chilli powder", "note": "Haveri"},
            {"name": "Hand-pounded mustard", "note": "Koppal"},
            {"name": "Sesame oil (oil-free option available)", "note": "Cold-pressed, Karnataka"},
            {"name": "Rock salt, fenugreek, asafoetida", "note": "No preservatives, no acetic acid"},
        ],
        "nutrition": [("Energy", "196 kcal"), ("Protein", "2.4 g"), ("Carbohydrates", "26.8 g"), ("— of which sugars", "11.4 g"),
                      ("Fat", "9.2 g"), ("— of which saturated", "1.1 g"), ("Dietary fibre", "6.1 g"), ("Sodium", "2.8 g")],
        "shelf_life": "15 months from the date of packing",
        "storage": "Keep the jar closed with a dry spoon. Refrigeration extends the colour but is not required.",
        "how_to_use": "One or two pieces with rice and ghee, or straight from the jar after a heavy lunch. Also excellent mashed into a plain dal.",
        "spice_level": "Medium",
        "made_by": {"name": "Nasreen Taj", "role": "Quality control assistant", "since": "2022",
                    "quote": "I test pH, salt and moisture for every batch. My signature is on the jar label — so I check every jar."},
        "sourced": {"farmer": "Girijamma H.", "village": "Hosadurga", "district": "Chitradurga", "crop": "Amla & tamarind", "since": "2022",
                    "quote": "Amla grows wild behind our field. I used to let it fall. Now it pays for my son's college bus pass."},
        "reviews": [
            {"name": "Ravi Shankar", "city": "Bengaluru", "rating": 5, "date": "Sep 2026",
             "text": "I am 62 and I have eaten a lot of amla pickle. This one has the right amount of jaggery — not a sweet jam, not pure vinegar."},
            {"name": "Anita D.", "city": "Mumbai", "rating": 5, "date": "May 2026",
             "text": "Ordered for my parents. They finished the jar in ten days and asked me for two more."},
        ],
    },
]

# -------------------------------------------------------------- testimonials
TESTIMONIALS = [
    {"type": "Farmer", "name": "Rudrappa H.", "role": "Chilli farmer · Byadagi, Haveri", "img": "assets/images/farmer-portrait.jpg",
     "quote": "Earlier the trader decided the weight and the price. Now I know the rate before I harvest, the weighing happens in front of me, and the money reaches my account in a week. That is all a farmer ever asked for."},
    {"type": "Farmer", "name": "Savitramma P.", "role": "Coriander farmer · Ron taluk, Gadag", "img": "assets/images/hands-spices.jpg",
     "quote": "In the third year they gave me seed and a soil test before sowing, and bought the whole crop at the agreed rate even when the market fell. I planted four acres more the next season."},
    {"type": "Our team", "name": "Shivamma B.", "role": "Masala unit lead · joined 2021", "img": "assets/images/factory-women.jpg",
     "quote": "I joined when my daughter was in Class 6. I had never used a machine or signed my name on a salary slip. Today I run the roasting line and my daughter is in Class 11 — her fees come from the fund."},
    {"type": "Our team", "name": "Bhavya R.", "role": "Packing team · joined 2024", "img": "assets/images/quality-control.jpg",
     "quote": "The first thing they asked was my daughter's school and class. Not my marks, not my experience — my daughter's school. That is when I decided to stay."},
    {"type": "Customer", "name": "Ananya R.", "role": "Bengaluru · customer since 2023", "img": "assets/images/hands-spices.jpg",
     "quote": "I bought the bisibelebath masala on a whim and now our entire building orders together. It tastes like the food my ajji made, and I like knowing whose chilli went into it."},
    {"type": "Partner", "name": "Preethi Stores", "role": "Retail partner · Yelahanka", "img": "assets/images/distribution.jpg",
     "quote": "We stock eleven brands of masala. ApnaPan is the only one where customers come back and ask for the farmer's name on the jar."},
]

# ------------------------------------------------------------------ timeline
TIMELINE = [
    {"year": "2019", "title": "Six women and a rented kitchen",
     "text": "Lakshmi Devi started ApnaPan in a rented kitchen shed in Doddaballapur with six women, two grinding stones and ₹40,000 of her own savings. The first product was one masala, sold to neighbours and a single store in Yelahanka.",
     "tags": ["6 women", "1 product"], "now": False},
    {"year": "2020", "title": "The lockdown that set our rules",
     "text": "When the mandis shut, we bought whatever our first 40 farmer families could harvest, at the previous year's rate, and stored it in a rented godown. We sold pickles and mixes directly to homes to survive. Our rule — buy at the farm gate, pay in 7 days — started here.",
     "tags": ["40 farmers", "Direct to homes"], "now": False},
    {"year": "2021", "title": "A licence, a lab, and the first label",
     "text": "FSSAI licensing let us sell in stores. We hired our first quality technician, Nasreen, printed our first proper label and moved to a 900 sq ft unit with a sealed packing room. Twenty-two women on the payroll.",
     "tags": ["FSSAI", "22 women"], "now": False},
    {"year": "2022", "title": "The Education Fund begins",
     "text": "A worker asked for a salary advance for her son's Class 10 exam fees. We paid it, and then decided no parent should ever have to ask. The Class 10 Fund was written into the company's articles: 6% of every sale goes into it, permanently.",
     "tags": ["38 children", "6% of every sale"], "now": False},
    {"year": "2023", "title": "Our own unit and our own quality lab",
     "text": "We moved into a 1,800 sq ft unit in the KIADB industrial area with a dedicated QC lab, a pickle kitchen, three packing lines and a creche room. 280 farmer partners, 64 women on the team, and 11 products in the catalogue.",
     "tags": ["Own unit", "1,800 sq ft", "64 women"], "now": False},
    {"year": "2025", "title": "Online, and 480 farmers deep",
     "text": "We started selling directly to homes across India, opened the Yelahanka experience store and crossed 480 farmer partners in six districts. Every product page began carrying the name of the farmer and the woman who made it.",
     "tags": ["480 farmers", "128 women", "216 children"], "now": False},
    {"year": "2026", "title": "Where we are today",
     "text": "128 women, 480 farmer families, 216 children in the education fund and 96,000 packs shipped last year. Our next unit near Kalaburagi will put us closer to our dal farmers and to a new team of women.",
     "tags": ["Unit #2 planned"], "now": True},
    {"year": "2030", "title": "Where we are going",
     "text": "Five units, 1,000 women on the payroll, 2,000 children in the education fund and 2,500 farmer partners — each new factory built around the crops of the district it sits in, and each one funded by the sales of the last.",
     "tags": ["Goal", "5 units", "1,000 women"], "now": False},
]

# --------------------------------------------------------------- for farmers
FARMER_WHY = [
    {"icon": "rupee", "title": "A price before you sow", "text": "We agree the rate for the season before planting, in writing, and hold it even if the market falls."},
    {"icon": "scale", "title": "Weighing you can watch", "text": "Electronic scale at the farm gate, printed slip, no deductions for 'moisture' or 'wastage' after loading."},
    {"icon": "clock", "title": "Payment in 7 days", "text": "Bank transfer within seven working days of delivery — usually three. No running credit."},
    {"icon": "seed", "title": "Seed, soil test and advice", "text": "Free soil testing, certified seed for chilli, coriander and groundnut, and an agronomist visit each season."},
    {"icon": "spark", "title": "Post-harvest training", "text": "Drying yards, moisture meters and grading training — the difference between ₹80 and ₹140 a kilo."},
    {"icon": "heart", "title": "We buy the whole lot", "text": "No cherry-picking the best bags. What you grow, we take — graded, but taken."},
]

FARMER_STEPS = [
    {"n": 1, "title": "Tell us about your farm", "text": "Send the form below or a WhatsApp message with your village, district, crops and expected quantity. Two minutes is enough."},
    {"n": 2, "title": "A visit from our field team", "text": "We come to your field within 10 days, look at the crop, take a soil sample and give you a written indicative rate."},
    {"n": 3, "title": "Sign the season agreement", "text": "A one-page agreement in Kannada: quantity, rate, delivery date, payment date, quality expectations. You keep a copy."},
    {"n": 4, "title": "Harvest, weigh and get paid", "text": "We collect at your village, weigh in front of you and transfer payment to your account within 7 working days."},
]

FARMER_FAQ = [
    {"q": "What is the minimum quantity you buy?",
     "a": "For chilli, coriander, turmeric, groundnut and dal we buy from 300 kg upwards. For mango midi and amla we buy from 200 kg. If you are a very small grower, we can group you with three or four neighbours in the same village and buy together."},
    {"q": "Do you pay above the mandi rate always?",
     "a": "Our agreement rate is set in advance and is on average 22% above the local mandi rate for the same grade — but the honest answer is that in some weeks the mandi goes higher than us. If the market rate rises by more than 10% before harvest, we revise your rate upward. We have never revised one downward."},
    {"q": "What quality do you look for?",
     "a": "Clean, sorted produce with proper drying. For chilli, under 10% moisture; for coriander, under 9%; no mould, no stones. We give you a moisture meter and teach you to use it — that alone raises your price by a grade."},
    {"q": "Are you certified organic?",
     "a": "We buy both organic and conventional produce and label each honestly. Our Jaivik Bharat certification for a small organic line is in process. We do not pay a premium for a certificate you do not have — bring us clean, properly dried produce and we pay for that."},
    {"q": "Do you buy from outside Karnataka?",
     "a": "For now our sourcing is 100% Karnataka — six districts. As we add processing capacity we will look at neighbouring states for mustard oil and select spices."},
]

# -------------------------------------------------------------------- career
JOBS = [
    {"title": "Spice Processing Technician", "dept": "Processing", "type": "Full-time", "location": "Doddaballapur unit",
     "pay": "₹18,000–24,000 / month", "exp": "0–2 years", "openings": 3,
     "about": "Run the roaster and the stone mill, keep batch records and check aroma and colour at every stage.",
     "asks": ["10th pass or above", "Willing to learn machine operation", "Basic Kannada or Hindi", "Comfortable with shift timings (6am–2pm / 2pm–10pm)"]},
    {"title": "Quality Control Assistant", "dept": "Quality", "type": "Full-time", "location": "Doddaballapur unit",
     "pay": "₹20,000–26,000 / month", "exp": "0–3 years", "openings": 2,
     "about": "Test moisture, salt, pH and microbial parameters for every batch, and sign off the release of each lot.",
     "asks": ["Diploma or BSc in Food Technology / Microbiology / Chemistry", "Careful documentation", "Willing to be trained on our lab equipment"]},
    {"title": "Packaging Team Lead", "dept": "Packaging", "type": "Full-time", "location": "Doddaballapur unit",
     "pay": "₹17,000–22,000 / month", "exp": "1–3 years", "openings": 1,
     "about": "Lead a seven-woman packing line, manage label accuracy on every SKU, and own hygiene and line speed.",
     "asks": ["Experience in a food or FMCG packing line", "Ability to lead a small team", "Good with numbers and count reconciliation"]},
    {"title": "Field Sourcing Coordinator", "dept": "Sourcing", "type": "Full-time", "location": "Kolar / Haveri / Gadag (field role)",
     "pay": "₹22,000–30,000 / month + travel allowance", "exp": "1–4 years", "openings": 2,
     "about": "Visit farmers, measure moisture, negotiate grade-wise rates with our price band, and organise collection.",
     "asks": ["Two-wheeler licence and willingness to travel 15 days a month", "Fluent Kannada", "Comfortable with a tablet/phone app for entries"]},
    {"title": "Accounts & Admin Executive", "dept": "Finance", "type": "Full-time", "location": "Yelahanka office",
     "pay": "₹25,000–32,000 / month", "exp": "2–5 years", "openings": 1,
     "about": "Farmer payment files, GST and TDS filing support, payroll for 128 team members, and the education fund ledger.",
     "asks": ["B.Com with Tally/Zoho Books", "Working knowledge of GST filing", "Attention to detail on farmer payment dates"]},
    {"title": "D2C & Social Media Associate", "dept": "Marketing", "type": "Full-time / hybrid", "location": "Yelahanka office",
     "pay": "₹28,000–38,000 / month", "exp": "1–3 years", "openings": 1,
     "about": "Run our Instagram and WhatsApp catalogues, write product copy, and turn farmer stories into content people trust.",
     "asks": ["Good written Kannada and English", "Comfortable shooting photos and short video on a phone", "Basic analytics"]},
]

BENEFITS = [
    {"icon": "rupee", "title": "Wages above the local average", "text": "Every role is benchmarked against the Doddaballapur industrial belt and we pay 12–18% above the median for the same skill level."},
    {"icon": "shield", "title": "PF, ESI and paid leave", "text": "Provident fund and ESI from day one, 20 days paid leave, festival advance, and six months of paid maternity leave."},
    {"icon": "school", "title": "Your child's education is funded", "text": "From your first month, your child is enrolled in the Class 10 Fund — fees, books, uniform, coaching and a tablet for high scorers."},
    {"icon": "spark", "title": "Real skill training", "text": "Food safety, machine operation, quality testing and accounts — certified courses, on paid work time, 4,800 hours last year."},
    {"icon": "bus", "title": "Travel and food", "text": "Free pick-up and drop on 12 routes across Doddaballapur, Yelahanka and Nelamangala, plus lunch at the unit."},
    {"icon": "women", "title": "A team built for women", "text": "Nine in ten of us are women, every supervisor is a woman, there is a creche room at the unit and an internal grievance committee."},
]

CAREER_FAQ = [
    {"q": "Do I need to be able to read and write English?",
     "a": "No. Most roles only need Kannada or Hindi. Where English is needed — accounts, marketing, quality documentation — we will teach you the specific words you need, and we run a weekly spoken-English class on paid time."},
    {"q": "I have never worked in a factory. Will you still consider me?",
     "a": "Yes. Half of our current team had never worked outside their home before joining. We train on the machine, in small groups, with a senior woman worker as your buddy for the first three months."},
    {"q": "What are the working hours and shifts?",
     "a": "Processing runs two shifts, 6am–2pm and 2pm–10pm. Packing runs 9am–6pm. Office roles are 9:30am–6:30pm, Monday to Saturday, with every alternate Saturday off. No night shift for women, no exceptions."},
    {"q": "Are these jobs only for women?",
     "a": "No. Every role is open to everyone and we assess on the same criteria. We are a women-led company — nine in ten of our team members are women — and we say this openly because it is our strength, not a barrier for anyone else."},
]

# --------------------------------------------------------------------- posts
POSTS = [
    {
        "slug": "why-we-pay-farmers-above-mandi-price",
        "title": "Why we pay 22% above the mandi — and how the maths still works",
        "excerpt": "Every spice brand says 'farm-direct'. Here is our actual cost sheet: what we pay, what we save, and where the premium comes from.",
        "category": "Sourcing",
        "date": "2026-08-14", "date_display": "14 August 2026", "read": "6 min read",
        "img": "assets/images/farmer-portrait.jpg",
        "author": "Lakshmi Devi R., Founder",
        "body": [
            ("p", "There is a version of 'farm-direct' where a company buys a truckload at the mandi, takes the photo opportunity at the farm gate and puts the farmer's face on a label. We have been asked to do that. We do not, because the arithmetic of buying at the farm gate actually works — but only if you are honest about all four numbers in it."),
            ("h2", "Number 1: what we pay"),
            ("p", "In 2025 our average purchase price across chilli, coriander, turmeric, dal, groundnut, amla and mango midi was 22% above the prevailing local mandi rate for the same grade. Our chilli rate to Rudrappa in Haveri was ₹138 a kilo against a mandi rate of ₹112. That premium is not charity and it is not marketing. It is the price of getting a specific grade — under 10% moisture, cleaned, sorted, and delivered in one lot instead of being mixed with three other farmers' bags."),
            ("h2", "Number 2: what the middleman actually costs us"),
            ("p", "When we began, we bought from commission agents. Between the agent's commission, the transporter's cut, the 'gunnysack shrink' that never quite added up, and the rejections after loading, we were paying 26–31% over the farm-gate rate to receive a grade we never fully controlled. Today we pay 22% over the farm gate and receive exactly the grade we asked for, weighed on a scale the farmer can see. The premium is roughly the difference we no longer give away to three people in the middle."),
            ("h2", "Number 3: what quality does to the rest of the factory"),
            ("p", "This is the number most people miss. Clean, dry, properly graded produce does not just taste better — it changes the whole production line. Moisture under 10% means the chilli roasts evenly, which means fewer burnt batches and less rework. Sorted produce means our women are not spending hours picking stones out of a conveyor. Across 2025, our rejection and rework losses fell from 7.1% to 3.4% of input. That is worth more to us than the entire premium we pay."),
            ("blockquote", "A farmer who is paid properly in April will dry his crop properly in June. That is not sentiment — it is supply chain management."),
            ("h2", "Number 4: what it costs the customer"),
            ("p", "A 200g jar of our masala is ₹185. A supermarket brand's 200g sachet is ₹99–₹120 with roughly a fifth of it fillers and anti-caking agents. Our price is higher because there is nothing in the jar except spice — no starch, no salt as a bulking agent, no colour. Per serving, our masala costs about ₹9; the cheap sachet costs ₹7 and needs more of it. We are not the cheapest. We are the one where more of the rupee goes to the person who grew the crop."),
            ("h2", "What we will not do"),
            ("p", "We will not buy from a farmer at a rate below the mandi and call it 'direct sourcing'. We will not deduct for moisture after the goods have left the village. And we will not tell you we are the cheapest masala in India. We are the one that can tell you the name of the farmer, the village, and the date the money was transferred."),
        ],
    },
    {
        "slug": "inside-the-class-10-fund",
        "title": "216 children, one classroom: inside the ApnaPan Class 10 Fund",
        "excerpt": "It started with a salary advance for exam fees. Six percent of every sale has gone into the fund since 2022 — here is exactly what it pays for.",
        "category": "Education",
        "date": "2026-07-02", "date_display": "2 July 2026", "read": "5 min read",
        "img": "assets/images/education-children.jpg",
        "author": "ApnaPan Team",
        "body": [
            ("p", "In March 2022, one of our packing team members asked for an advance of ₹7,400. Her son's Class 10 board fees were due, along with the coaching class payment that most parents in her neighbourhood consider unavoidable. She had worked with us for eleven months. We paid it, and then we sat down and wrote a rule that made sure nobody would ever have to ask again."),
            ("h2", "Six percent, permanently"),
            ("p", "Six percent of the value of every single sale now goes into the Class 10 Fund. It is written into the company's articles of association, which means it cannot be quietly dropped in a lean quarter — the fund is a payment obligation, ranked the same way as a farmer's invoice. Since 2022 that has put ₹1.9 crore into the fund and covered 216 children."),
            ("h2", "What the fund actually pays for"),
            ("p", "Every child of every employee is enrolled the month their parent joins, whether or not the child is anywhere near Class 10. The support is graded:"),
            ("ul", [
                "Classes 1 to 9: textbooks, notebooks, uniforms and a school bag every year",
                "Class 10: full school and board exam fees, coaching in maths and science, bus or cycle pass, and a study tablet for children scoring above 75% in the Class 9 exam",
                "Class 11 and 12: fees continue for children who stay in school",
                "₹5,000 grant on passing Class 10 with distinction, paid to the child directly",
            ]),
            ("h2", "The result we did not plan for"),
            ("p", "Before the fund, four or five women left the company every year, usually in March, usually to earn more during the exam and admission season. In 2025, attrition in the packing and processing teams was one person. When a parent does not have to choose between this month's rent and their child's fees, they stay, they learn the next machine, and they lead. Our education spend is the cheapest retention programme we have ever run."),
            ("blockquote", "I joined when my daughter was in Class 6. Her fees come from the fund now and she is in Class 11. I run the roasting line. I still cannot quite say those two sentences without smiling. — Shivamma B., masala unit lead"),
            ("h2", "How we will report it"),
            ("p", "Roughly every quarter we publish the fund's income, what was disbursed, and the pass rate of the cohort on our impact page. The children's names are never published — parents decide whether their child appears in any photograph. The numbers are audited along with our annual accounts, because a promise like this should be checkable, not just believable."),
        ],
    },
    {
        "slug": "byadagi-chilli-guide",
        "title": "Byadagi chilli: the deep red that makes Karnataka food taste like home",
        "excerpt": "Why the chilli of one taluk in Haveri behaves differently in a pan — and how to tell a genuine Byadagi from a look-alike.",
        "category": "Ingredients",
        "date": "2026-06-11", "date_display": "11 June 2026", "read": "4 min read",
        "img": "assets/images/hands-spices.jpg",
        "author": "Sunita K., Production Supervisor",
        "body": [
            ("p", "If you have eaten a proper Karnataka bisibelebath, you have eaten Byadagi chilli. It is the reason the dish glows red without setting fire to your mouth — and the reason a masala from one district tastes different from a masala made to the same recipe two hundred kilometres away."),
            ("h2", "Why this chilli, and this place"),
            ("p", "Byadagi, a taluk in Haveri district in northern Karnataka, grows a long, wrinkled, dark-red chilli with a thin skin and a very high colour value. Its heat is moderate — around 12,000 to 15,000 Scoville units against the 30,000-plus of Guntur — but its oleoresin content is among the highest in India. In practice that means colour and aroma without brutality. Two-thirds of the colour in a masala can come from the chilli itself, so we add no colour and no paprika extract."),
            ("h2", "Reading a Byadagi chilli"),
            ("ul", [
                "Colour: deep brick red with a dark sheen, never bright orange (that is usually a Guntur or Kashmiri mix)",
                "Skin: thin, wrinkled and slightly translucent — press a nail into it and it should leave a faint line, not crack",
                "Smell: sweet, almost raisin-like when broken; a bitter, dusty smell means over-drying or old stock",
                "Stalk: short and pale, easily snapped. A long, glossy stalk often means it was harvested before fully ripening",
            ]),
            ("h2", "What we do differently"),
            ("p", "We buy chilli only in December to March, from the late harvest when the colour value peaks, and we check moisture on the farm with our own meter — the difference between 9% and 13% moisture is the difference between a masala that lasts nine months and one that goes flat in three. In the unit, we dry the chilli in the shade for two days before roasting, which keeps the red from turning brown. Our roaster, Shivamma, decides the roast point by smell, not by the clock."),
            ("blockquote", "Under-roast and the chilli is raw and bitter. Over-roast by thirty seconds and the whole batch is dark and tasting of smoke. So you stand there, and you smell, and you decide. — Shivamma B."),
            ("h2", "Can you substitute it?"),
            ("p", "You can. Kashmiri chilli gives you colour with even less heat; Guntur gives you heat with less colour. But if you want a Karnataka dish to taste like Karnataka, Byadagi is the chilli — and the good news is that for ₹20 more than a supermarket blend, you can have the real one, from a farmer whose name is on the jar."),
        ],
    },
    {
        "slug": "mavina-midi-pickle-calendar",
        "title": "Mavina midi in June: a pickle calendar from our kitchen",
        "excerpt": "Fourteen days of sun, twelve kilos of mustard and a one-day window: how baby mango pickle is actually made, week by week.",
        "category": "How we make it", "date": "2026-05-28", "date_display": "28 May 2026", "read": "5 min read",
        "img": "assets/images/products/mavina-midi-pickle.jpg",
        "author": "Gowramma D., Pickle Kitchen Lead",
        "body": [
            ("p", "Mavina midi — the tiny baby mango, no bigger than your thumb, with a stone so soft you can eat it whole — has a season of about three weeks. Miss it and there is no pickle. That is why our pickle kitchen runs to a calendar that would look absurd in any other part of the business."),
            ("h2", "Late May: the 'go' decision"),
            ("p", "Our field coordinator walks the orchards in Kolar and Ramanagara with a refractometer and a knife. The midi must be acidic enough to cure, firm enough to hold its shape after salting, and the stone soft enough that the fruit is not bitter. When three orchards in a row are right, we say go, and the pickers start the next morning at 5am while the fruit is cool."),
            ("h2", "The 24-hour rule"),
            ("p", "From plucking to salt: twenty-four hours. Not because it is traditional, but because the fruit begins to soften and lose acidity after that, and no amount of oil or chilli rescues a soft midi. Fruit comes to the unit in cotton sacks, is washed, wiped dry in a single layer under fans, and the tip of each mango is split with a small knife so the brine can reach the stone. This part is handwork, and fifty women do it at two long tables."),
            ("h2", "Days 1 to 3: the salt"),
            ("p", "The midis go into food-grade drums in layers — fruit, hand-pounded rock salt, fruit, salt — and are turned twice a day. Salt draws out water, tightens the skin and creates the brine the pickle will live in for the next year. We use no acetic acid and no vinegar: the salt and the fruit acidity do the work."),
            ("h2", "Days 4 to 14: sun and mustard"),
            ("p", "Fruit, dried in the shade, is packed with hand-pounded mustard, Byadagi chilli powder, fenugreek, turmeric and asafoetida, then covered with cold-pressed mustard oil and left on the terrace in clear glass jars — fourteen days of it, brought in before the afternoon thunder. Every morning at seven, someone stirs every single jar with a dry wooden ladle. On day fourteen we taste, and we decide whether the batch goes into jars today or waits two more days."),
            ("blockquote", "You cannot hurry midi. The pickle is ready when the mango gives in a little under your thumb. If you jar it early, it stays crunchy and tastes raw forever. — Gowramma D."),
            ("h2", "And then it keeps improving"),
            ("p", "A mavina midi pickle is at its best between month three and month nine, and perfectly good at eighteen. Keep a dry spoon in the house, keep the fruit under the oil, and do not put it in the fridge before you open it. If you take three midis with curd rice on a hot afternoon, you will understand why we rearrange our entire year for a three-week season."),
        ],
    },
    {
        "slug": "what-women-led-means-in-a-factory",
        "title": "What 'women-led' actually means inside a food factory",
        "excerpt": "Not a pink logo. It means who owns the machines, who signs the batch, who sets the shift timings — and who gets promoted.",
        "category": "Our team", "date": "2026-04-09", "date_display": "9 April 2026", "read": "5 min read",
        "img": "assets/images/factory-women.jpg",
        "author": "Lakshmi Devi R., Founder",
        "body": [
            ("p", "'Women-led' is printed on more spice packets in India than you can count. It usually means a photograph of a woman on the front. I would like to describe what it means at our unit, so that you can ask the same questions of any brand that uses the phrase."),
            ("h2", "It means who operates and owns the machines"),
            ("p", "Every supervisor at ApnaPan is a woman — roasting, grinding, packing, pickle kitchen, quality. The heaviest equipment we operate, the roaster and the batch mixer, is run by women who were trained on it internally. When we bought our second packing line last year, three women from the first line designed the workflow for it, because they knew where the bottleneck actually was."),
            ("h2", "It means who signs the batch"),
            ("p", "Our quality lab is run by Nasreen Taj, who has authority to stop production. Every jar carries a batch code that traces to her signature. If she rejects a lot, it is rejected — the founder does not get to overrule her. There is no version of this company where a woman's technical judgement is advisory only."),
            ("h2", "It means the shift timings"),
            ("p", "No night shifts for women, ever, even though the equipment can run overnight. Two shifts, 6am–2pm and 2pm–10pm, with 12 pick-up-and-drop routes so nobody is walking home in the dark. There is a creche room at the unit and school-holiday childcare. These are not perks bolted on; they are the reason the team is stable."),
            ("h2", "It means who gets promoted"),
            ("p", "Bhavya joined the packing line in 2024 and now operates the sealing machine and is training on the mixer. Shivamma joined in 2021 and runs the roasting line. Of our eleven supervisors and above, seven are women who were promoted from within. We post every vacancy internally first, with the pay band written on the notice, and we pay the band regardless of who takes the role."),
            ("h2", "What we are still not good at"),
            ("p", "Two things. The first is that while our production team is 90% women, our field sourcing team is mostly men, because the role needs a two-wheeler and long travel in districts where women travel less freely — we are hiring and training two women into field roles this year and I will report how it goes. The second is that the ghee roast and Mangaluru lines sell more than the others, and I would like to stop pretending that our best-selling product should not also be our best-paying one. We raised the processing wage band by 8% in January, and I think we can do better still."),
            ("p", "If a brand says women-led, ask what the women run. Not whether they are in the picture — whether they can stop the line."),
        ],
    },
]

# ----------------------------------------------------------------------- FAQ
FAQS_HOME = [
    {"q": "Is ApnaPan a women-run company?",
     "a": "Yes. Nine of our ten team members are women and every supervisor on the factory floor is a woman. Our quality head can stop production, and 7 of our 11 supervisors were promoted from within."},
    {"q": "Where does your produce come from?",
     "a": "100% of it from Karnataka — 480 farmer families across six districts (Bengaluru Rural, Kolar, Chikkaballapur, Ramanagara, Mandya, Tumakuru) plus partner growers in Haveri, Gadag, Koppal and Chitradurga. Every product page names the farmer."},
    {"q": "Do you use preservatives or artificial colours?",
     "a": "No. No preservatives, no artificial colours, no anti-caking agents and no bulking starches. Our masalas are spice, dal, copra and salt — nothing else."},
    {"q": "How does my purchase fund a child's education?",
     "a": "Six percent of the value of every sale goes into the Class 10 Fund, written into the company's articles. It pays school fees, books, uniforms, coaching and exam fees for 216 children of our employees."},
]

FAQS_SHIPPING = [
    {"q": "Where do you deliver and how much does it cost?", "a": "We deliver across India. Free shipping on orders above ₹599; a flat ₹49 below that. Bengaluru orders usually arrive in 1–2 days, the rest of India in 3–6 days."},
    {"q": "How long do the products stay fresh?", "a": "Masalas and mixes: 6–9 months from packing, printed on the pack. Pickles: 15–18 months. We roast and grind in small batches every Tuesday and Friday, so the pack you receive was usually made within the last three weeks."},
    {"q": "What is your returns policy?", "a": "If anything arrives damaged, leaking or is not what you ordered, tell us within 7 days on WhatsApp and we replace it or refund it — no photographs of forms required if it is clearly our mistake. Taste is a fair reason too: if a masala genuinely does not work for you, we will refund your first jar."},
    {"q": "Do you sell wholesale or for gifting?", "a": "Yes. Retail and distribution partners from 24 units per SKU, and corporate gifting from 50 boxes with custom labels. Write to hello@apnapan.in or use the form on our contact page."},
]
